name: De Bana Live Bot
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests pillow
      - run: python bot.py
        env:
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_TOKEN: ${{ secrets.FB_TOKEN }}
